name: noor_funds
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.2.1
  camera: ^0.10.5+5
  image_picker: ^1.0.4


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  google_ml_kit: ^0.16.3
  csv: ^5.0.1
  excel: ^2.0.0
  web: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - .env
